version: '2'
services:

  ####### infrastructure

  elasticsearch:
    image: elasticsearch

  kibana:
    image: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200

  logstash:
    build: ./logstash
    environment:
      ELK_ES_HOST: elasticsearch:9200
      ELK_LOGSTASH_UDP_PORT: 21398
    ports:
      - "localhost:21398:21398/udp"

  ####### services

  testapp:
    image: node:6-alpine
    command: node .
    volumes:
      - ${TT_PROJECTS}/testapp:/app:ro
    working_dir: /app
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:21398
    labels:
       com.tarantino.source: git@github.com:meet-tarantino/testapp.git
